### ISSUE TITLE
Mockito Error on Some Local Development Environment

### ISSUE THREAD

**Issue by VincenzoFerme** [benchflow/benchflow#255]
Example of error log for the `experiment-manager`:

```
[ERROR] validRequest(cloud.benchflow.experimentmanager.resources.BenchFlowExperimentResourceTest)  Time elapsed: 0.004 s  <<< ERROR!
org.mockito.exceptions.base.MockitoException:

Mockito cannot mock this class: interface java.util.concurrent.ExecutorService

Mockito can only mock visible & non-final classes.
If you're not sure why you're getting this error, please report to the mailing list.

Underlying exception : java.lang.IllegalArgumentException: java.lang.ClassCastException@70e9c95d
	at cloud.benchflow.experimentmanager.resources.BenchFlowExperimentResourceTest.<init>(BenchFlowExperimentResourceTest.java:37)
Caused by: java.lang.IllegalArgumentException: java.lang.ClassCastException@70e9c95d
	at cloud.benchflow.experimentmanager.resources.BenchFlowExperimentResourceTest.<init>(BenchFlowExperimentResourceTest.java:37)

[ERROR] invalidExperimentID(cloud.benchflow.experimentmanager.resources.BenchFlowExperimentResourceTest)  Time elapsed: 0 s  <<< ERROR!
org.mockito.exceptions.base.MockitoException:

Mockito cannot mock this class: interface java.util.concurrent.ExecutorService

Mockito can only mock visible & non-final classes.
If you're not sure why you're getting this error, please report to the mailing list.

Underlying exception : java.lang.IllegalArgumentException: java.lang.ClassCastException@2794eab6
	at cloud.benchflow.experimentmanager.resources.BenchFlowExperimentResourceTest.<init>(BenchFlowExperimentResourceTest.java:37)
Caused by: java.lang.IllegalArgumentException: java.lang.ClassCastException@2794eab6
	at cloud.benchflow.experimentmanager.resources.BenchFlowExperimentResourceTest.<init>(BenchFlowExperimentResourceTest.java:37)

[INFO] Running cloud.benchflow.experimentmanager.services.external.MinioServiceTest
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0 s - in cloud.benchflow.experimentmanager.services.external.MinioServiceTest
[INFO] Running cloud.benchflow.experimentmanager.tasks.RunBenchFlowExperimentTaskTest
[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.512 s <<< FAILURE! - in cloud.benchflow.experimentmanager.tasks.RunBenchFlowExperimentTaskTest
[ERROR] run(cloud.benchflow.experimentmanager.tasks.RunBenchFlowExperimentTaskTest)  Time elapsed: 0.501 s  <<< ERROR!
java.lang.VerifyError:
Uninitialized object exists on backward branch 209
Exception Details:
  Location:
    scala/collection/immutable/HashMap$HashTrieMap.split()Lscala/collection/immutable/Seq; @249: goto
  Reason:
    Error exists in the bytecode
  Bytecode:
    0000000: 2ab6 0057 04a0 001e b200 afb2 00b4 04bd
    0000010: 0002 5903 2a53 c000 b6b6 00ba b600 bec0
    0000020: 00c0 b02a b600 31b8 003b 3c1b 04a4 015e
    0000030: 1b05 6c3d 2a1b 056c 2ab6 0031 b700 c23e
    0000040: 2ab6 0031 021d 787e 3604 2ab6 0031 0210
    0000050: 201d 647c 7e36 05bb 0014 59b2 00b4 2ab6
    0000060: 0033 c000 b6b6 00c6 b700 c91c b600 cd3a
    0000070: 0619 06c6 001a 1906 b600 d1c0 007d 3a07
    0000080: 1906 b600 d4c0 007d 3a08 a700 0dbb 00d6
    0000090: 5919 06b7 00d9 bf19 073a 0919 083a 0abb
    00000a0: 0002 5915 0419 09bb 0014 59b2 00b4 1909
    00000b0: c000 b6b6 00c6 b700 c903 b800 df3a 0e3a
    00000c0: 0d03 190d b900 e301 0019 0e3a 1136 1036
    00000d0: 0f15 0f15 109f 0027 150f 0460 1510 190d
    00000e0: 150f b900 e602 00c0 0005 3a17 1911 1917
    00000f0: b800 ea3a 1136 1036 0fa7 ffd8 1911 b800
    0000100: eeb7 005c 3a0b bb00 0259 1505 190a bb00
    0000110: 1459 b200 b419 0ac0 00b6 b600 c6b7 00c9
    0000120: 03b8 00df 3a13 3a12 0319 12b9 00e3 0100
    0000130: 1913 3a16 3615 3614 1514 1515 9f00 2715
    0000140: 1404 6015 1519 1215 14b9 00e6 0200 c000
    0000150: 053a 1819 1619 18b8 00f1 3a16 3615 3614
    0000160: a7ff d819 16b8 00ee b700 5c3a 0cb2 00f6
    0000170: b200 b405 bd00 0259 0319 0b53 5904 190c
    0000180: 53c0 00b6 b600 bab6 00f9 b02a b600 3303
    0000190: 32b6 00fb b0
  Stackmap Table:
    same_frame(@35)
    full_frame(@141,{Object[#2],Integer,Integer,Integer,Integer,Integer,Object[#105]},{})
    append_frame(@151,Object[#125],Object[#125])
    full_frame(@209,{Object[#2],Integer,Integer,Integer,Integer,Integer,Object[#105],Object[#125],Object[#125],Object[#125],Object[#125],Top,Top,Object[#20],Object[#55],Integer,Integer,Object[#103]},{Uninitialized[#159],Uninitialized[#159],Integer,Object[#125]})
    full_frame(@252,{Object[#2],Integer,Integer,Integer,Integer,Integer,Object[#105],Object[#125],Object[#125],Object[#125],Object[#125],Top,Top,Object[#20],Object[#55],Integer,Integer,Object[#103]},{Uninitialized[#159],Uninitialized[#159],Integer,Object[#125]})
    full_frame(@312,{Object[#2],Integer,Integer,Integer,Integer,Integer,Object[#105],Object[#125],Object[#125],Object[#125],Object[#125],Object[#2],Top,Object[#20],Object[#55],Integer,Integer,Object[#103],Object[#20],Object[#55],Integer,Integer,Object[#103]},{Uninitialized[#262],Uninitialized[#262],Integer,Object[#125]})
    full_frame(@355,{Object[#2],Integer,Integer,Integer,Integer,Integer,Object[#105],Object[#125],Object[#125],Object[#125],Object[#125],Object[#2],Top,Object[#20],Object[#55],Integer,Integer,Object[#103],Object[#20],Object[#55],Integer,Integer,Object[#103]},{Uninitialized[#262],Uninitialized[#262],Integer,Object[#125]})
    full_frame(@395,{Object[#2],Integer},{})

	at cloud.benchflow.experimentmanager.tasks.RunBenchFlowExperimentTaskTest.run(RunBenchFlowExperimentTaskTest.java:120)

[INFO]
[INFO] Results:
[INFO]
[ERROR] Errors:
[ERROR]   BenchFlowExperimentResourceTest.<init>:37 Mockito
Mockito cannot mock this cl...
[ERROR]   BenchFlowExperimentResourceTest.<init>:37 Mockito
Mockito cannot mock this cl...
[ERROR]   RunBenchFlowExperimentTaskTest.run:120 » Verify Uninitialized object exists on...
[INFO]
```

**Comment by VincenzoFerme** [comment]
I also got:

```
[ERROR] Tests run: 2, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 33.427 s <<< FAILURE! - in cloud.benchflow.experimentmanager.BenchFlowExperimentManagerApplicationIT
[ERROR] runInvalidExperiment(cloud.benchflow.experimentmanager.BenchFlowExperimentManagerApplicationIT)  Time elapsed: 7.211 s  <<< ERROR!
javax.ws.rs.ProcessingException: java.net.SocketTimeoutException: Read timed out
	at cloud.benchflow.experimentmanager.BenchFlowExperimentManagerApplicationIT.runInvalidExperiment(BenchFlowExperimentManagerApplicationIT.java:77)
Caused by: java.net.SocketTimeoutException: Read timed out
	at cloud.benchflow.experimentmanager.BenchFlowExperimentManagerApplicationIT.runInvalidExperiment(BenchFlowExperimentManagerApplicationIT.java:77)
```

**Comment by VincenzoFerme** [comment]
For the first error, the solution (that has to be documented) should be to let maven refer to the correct JDK, and use the most recent JDK 8. See: http://stackoverflow.com/a/10363924 and http://stackoverflow.com/a/19324816
