### ISSUE TITLE
Integrate minio-client library

### ISSUE THREAD

**Issue by jeppe-style** [benchflow/benchflow#268]
Replace existing minio client with the one from the benchflow-minio-client library.

**Comment by VincenzoFerme** [comment]
Take also care of

Silently fails:

```Java
ERROR [2017-08-03 14:13:53,997] MinioService: Exception in copyObject: from:benchflow/alwaysCompleted/1/1/docker-compose.yml to:4e4c/BenchFlow/alwaysCompleted-1/1/docker-compose.yml
! io.minio.errors.ErrorResponseException: The specified key does not exist.
! at io.minio.MinioClient.execute(MinioClient.java:922)
! at io.minio.MinioClient.executeGet(MinioClient.java:1001)
! at io.minio.MinioClient.getObject(MinioClient.java:1310)
! at io.minio.MinioClient.getObject(MinioClient.java:1224)
! at cloud.benchflow.experimentmanager.services.external.MinioService.copyObject(MinioService.java:311)
! at cloud.benchflow.experimentmanager.services.external.MinioService.copyDeploymentDescriptorForDriversMaker(MinioService.java:165)
! at cloud.benchflow.experimentmanager.services.external.MinioService$MockitoMock$275255387.copyDeploymentDescriptorForDriversMaker$accessor$c5tZZhct(Unknown Source)
! at cloud.benchflow.experimentmanager.services.external.MinioService$MockitoMock$275255387$auxiliary$fVUII8qD.call(Unknown Source)
! at org.mockito.internal.creation.bytebuddy.InterceptedInvocation$SuperMethod$FromCallable.invoke(InterceptedInvocation.java:188)
! at org.mockito.internal.creation.bytebuddy.InterceptedInvocation.callRealMethod(InterceptedInvocation.java:125)
! at org.mockito.internal.stubbing.answers.CallsRealMethods.answer(CallsRealMethods.java:40)
! at org.mockito.Answers.answer(Answers.java:91)
! at org.mockito.internal.handler.MockHandlerImpl.handle(MockHandlerImpl.java:97)
! at org.mockito.internal.handler.NullResultGuardian.handle(NullResultGuardian.java:29)
! at org.mockito.internal.handler.InvocationNotifierHandler.handle(InvocationNotifierHandler.java:37)
! at org.mockito.internal.creation.bytebuddy.MockMethodInterceptor.doIntercept(MockMethodInterceptor.java:36)
! at org.mockito.internal.creation.bytebuddy.MockMethodInterceptor.access$000(MockMethodInterceptor.java:17)
! at org.mockito.internal.creation.bytebuddy.MockMethodInterceptor$DispatcherDefaultingToRealMethod.interceptSuperCallable(MockMethodInterceptor.java:96)
! at cloud.benchflow.experimentmanager.services.external.MinioService$MockitoMock$275255387.copyDeploymentDescriptorForDriversMaker(Unknown Source)
! at cloud.benchflow.experimentmanager.tasks.start.StartTask.saveDriversMakerCompatibleFilesOnMinio(StartTask.java:128)
! at cloud.benchflow.experimentmanager.tasks.start.StartTask.call(StartTask.java:81)
! at cloud.benchflow.experimentmanager.tasks.start.StartTask.call(StartTask.java:28)
! at java.util.concurrent.FutureTask.run(FutureTask.java:266)
! at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
! at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
! at java.lang.Thread.run(Thread.java:748)
```
