### ISSUE TITLE
Exceptions when running EndpointTest

### ISSUE THREAD

**Issue by jeppe-style** [benchflow/benchflow#320]
For some resources there is the exception below. This is due to that a test is scheduled and fails, however, the endpoint test works since it is only testing that the return value is correct.

```
[INFO] Running cloud.benchflow.testmanager.resources.BenchFlowTestEndpointTest
Exception in thread "Thread-1" java.lang.NullPointerException
	at cloud.benchflow.testmanager.tasks.start.StartTask.run(StartTask.java:71)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by VincenzoFerme** [comment]
Other errors:

```
[ERROR] runValidExperiment(cloud.benchflow.experimentmanager.BenchFlowExperimentManagerApplicationIT)  Time elapsed: 3.933 s  <<< ERROR!
javax.ws.rs.ProcessingException: java.net.SocketTimeoutException: Read timed out
	at cloud.benchflow.experimentmanager.BenchFlowExperimentManagerApplicationIT.runValidExperiment(BenchFlowExperimentManagerApplicationIT.java:146)
Caused by: java.net.SocketTimeoutException: Read timed out
	at cloud.benchflow.experimentmanager.BenchFlowExperimentManagerApplicationIT.runValidExperiment(BenchFlowExperimentManagerApplicationIT.java:146)
```

Example: https://app.wercker.com/BenchFlow/benchflow/runs/build-benchflow-experiment-manager/5911d4a42add12000157a6e9?step=5911d4ba36e8d300012a83eb
