### ISSUE TITLE
Illegal run status (unknown) from Faban

### ISSUE THREAD

**Issue by jeppe-style** [benchflow/benchflow#409]
during execution of an experiment following error occurred and stopped the progress

```
benchflow-experiment-manager_1  | java.util.concurrent.ExecutionException: cloud.benchflow.faban.client.exceptions.IllegalRunStatusException: RunId jespertest_TestExploreUsersOnCamunda750_5_3.1Ureturned illegal run status UNKNOWN
benchflow-experiment-manager_1  | 
benchflow-experiment-manager_1  | 	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
benchflow-experiment-manager_1  | 	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
benchflow-experiment-manager_1  | 	at cloud.benchflow.experimentmanager.scheduler.ExperimentTaskScheduler.handleDetermineAndExecuteTrials(ExperimentTaskScheduler.java:193)
benchflow-experiment-manager_1  | 	at cloud.benchflow.experimentmanager.scheduler.ExperimentTaskScheduler.handleRunningState(ExperimentTaskScheduler.java:156)
benchflow-experiment-manager_1  | 	at cloud.benchflow.experimentmanager.scheduler.ExperimentTaskScheduler.handleExperimentState(ExperimentTaskScheduler.java:95)
benchflow-experiment-manager_1  | 	at cloud.benchflow.experimentmanager.scheduler.ExperimentDispatcher.run(ExperimentDispatcher.java:69)
benchflow-experiment-manager_1  | 	at java.lang.Thread.run(Thread.java:748)
benchflow-experiment-manager_1  | Caused by: cloud.benchflow.faban.client.exceptions.IllegalRunStatusException: RunId jespertest_TestExploreUsersOnCamunda750_5_3.1Ureturned illegal run status UNKNOWN
```

We should handle the `UNKNOWN` case without any runtime exception in [RunStatus.java](https://github.com/benchflow/benchflow/blob/devel/benchflow-faban-client/src/main/java/cloud/benchflow/faban/client/responses/RunStatus.java)

**Comment by VincenzoFerme** [comment]
Fix considering moving to managed exceptions:

- https://10kloc.wordpress.com/2013/03/09/runtimeexceptions-try-catch-or-not-to-catch/
- http://www.javapractices.com/topic/TopicAction.do?Id=129

**Comment by VincenzoFerme** [comment]
@jeppe-style this workaround https://github.com/benchflow/benchflow/issues/410 did not work, because we got the `UKNOWN` status again.
