### ISSUE TITLE
Error reading some files from Google Drive

### ISSUE THREAD

**Issue by VincenzoFerme** [benchflow/benchflow#75]
_From @igormoreno on November 12, 2016 18:56_

When reading from Google Drive the backup file:
[file-0 (1).txt](https://github.com/benchflow/data-manager/files/586296/file-0.1.txt)

the application crashes with the following error:
```
[error] application - 

! @7238i67je - Internal server error, for (GET) [/read-backup/51] ->
 
play.api.http.HttpErrorHandlerExceptions$$anon$1: Execution exception[[NullPointerException: null]]
        at play.api.http.HttpErrorHandlerExceptions$.throwableToUsefulException(HttpErrorHandler.scala:280)
        at play.api.http.DefaultHttpErrorHandler.onServerError(HttpErrorHandler.scala:206)
        at play.api.GlobalSettings$class.onError(GlobalSettings.scala:160)
        at play.api.DefaultGlobal$.onError(GlobalSettings.scala:188)
        at play.api.http.GlobalSettingsHttpErrorHandler.onServerError(HttpErrorHandler.scala:98)
        at play.core.server.netty.PlayRequestHandler$$anonfun$2$$anonfun$apply$1.applyOrElse(PlayRequestHandler.scala:100)
        at play.core.server.netty.PlayRequestHandler$$anonfun$2$$anonfun$apply$1.applyOrElse(PlayRequestHandler.scala:99)
        at scala.concurrent.Future$$anonfun$recoverWith$1.apply(Future.scala:344)
        at scala.concurrent.Future$$anonfun$recoverWith$1.apply(Future.scala:343)
        at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32)
Caused by: java.lang.NullPointerException: null
        at com.google.api.client.googleapis.media.MediaHttpDownloader.download(MediaHttpDownloader.java:186)
        at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeMediaAndDownloadTo(AbstractGoogleClientRequest.java:562)
        at com.google.api.services.drive.Drive$Files$Get.executeMediaAndDownloadTo(Drive.java:2717)
        at datastorages.googledrive.GoogleDrive.downloadStream(GoogleDrive.java:164)
        at datastorages.GoogleDriveStorage$$anonfun$read$2$$anonfun$apply$1.apply(DataStorage.scala:104)
        at datastorages.GoogleDriveStorage$$anonfun$read$2$$anonfun$apply$1.apply(DataStorage.scala:102)
        at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:252)
        at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:252)
        at scala.collection.Iterator$class.foreach(Iterator.scala:742)
        at scala.collection.AbstractIterator.foreach(Iterator.scala:1194)
```

I suspect this problem could actually be a bug in the Google API code I'm using to access Google Drive because reading the following file works perfectly:
[file-0.txt](https://github.com/benchflow/data-manager/files/586293/file-0.txt)

References:
https://github.com/vparfonov/google-api-java-client/blob/master/google-api-client/src/main/java/com/google/api/client/googleapis/media/MediaHttpDownloader.java

_Copied from original issue: benchflow/data-manager#22_

**Comment by VincenzoFerme** [comment]
Maybe is a bug with the name? Use file names without spaces, and only `-` or  `_` separated.

**Comment by VincenzoFerme** [comment]
_From @igormoreno on November 17, 2016 12:42_

The file names are the same. On Google drive they are both called file-0.txt (the additional " (1)" was added by the browser when I downloaded).
